# Makefile for the Epson "Model F" S1D135x1 driver
obj-$(CONFIG_FB_MODELF)           += modelffb.o
modelf_pl_hardware-y              := pl_hardware.o
obj-$(CONFIG_MODELF_PL_HARDWARE)  += modelf_pl_hardware.o

